### ISSUE TITLE
Don't add border-box to all elements

### ISSUE THREAD

**Issue by gtrufitt** [at-import/toolkit#23]
I know, it sounds like madness, but sometimes I don't want to add:

```
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  *behavior: url('/stylesheets/../behaviors/box-sizing/boxsizing.php');
} 
```

But I couldn't work out how to not add it - Is there a way?

**Comment by Snugug** [comment]
Use `@import "toolkit-no-css";` instead of `@import "toolkit";`. This will import all of Toolkit, minus the items pieces that write out CSS, including Box Sizing and Image/Video fluid CSS. All of the mixins and extendable calsses will be available.

Additionally, if you do not need support for IE<8, I'd encourage you to [turn off support for them](http://compass-style.org/reference/compass/support/), which, amongst other things, will remove the behavior from the `border-box` call. It will also help determine which clearfix Toolkit writes.

**Comment by gtrufitt** [comment]
Wonderful, thanks!
